### ISSUE TITLE
Fix for Russian translation

### ISSUE THREAD

**Issue by lmhs** [petrkle/periodic-table#12]
There are several words incorrectly translated to the Russian:
F.e.:
```
msgid "Italian"
msgstr "итальянец"
```
Here "Итальянский" should be used, as it is not a nationality but language

**Comment by Ckpuna4** [comment]
Hi, I'll fix it

**Comment by petrkle** [comment]
Thanks!

**Comment by petrkle** [comment]
Marged https://github.com/petrkle/periodic-table/pull/14/commits/9bd33724a69fcb2abe54624dad7a88242be32597

**Comment by lmhs** [comment]
Hello @petrkle!
I have found some more incorrect words in Russian translation
