### ISSUE TITLE
Vietnamese translation

### ISSUE THREAD

**Issue by petrkle** [petrkle/periodic-table#5]
Add vi_VN.po file with Vietnamese translation.

**Comment by martishevich** [comment]
@petrkle Would the translation from the Google Translate be enough?

**Comment by petrkle** [comment]
I prefer translations from native speakers.

**Comment by petrkle** [comment]
@martishevich Are you interested about Belarusian translation?

**Comment by martishevich** [comment]
@petrkle Yes, i can do it. Maybe create issue and assign it to me.

**Comment by petrkle** [comment]
Added https://github.com/petrkle/periodic-table/issues/6

**Comment by GustavoZiaugra** [comment]
Need translate to PT-BR?

**Comment by petrkle** [comment]
@GustavoZiaugra [pt_BR.po](https://github.com/petrkle/periodic-table/blob/master/po/pt_BR.po) alredy exist. You can check it for typos and other errors.

**Comment by GustavoZiaugra** [comment]
@petrkle 
I just checked the translation file and it is correct, if you need translation to portuguese from portugal or spanish, please advise.
Thank you.

**Comment by petrkle** [comment]
Maybe next hacktoberfest.
